### PR TITLE
Allow fully qualified classnames for gateway type

### PR DESCRIPTION
**Pull request by CHH**
This enables support for fully qualified classnames as gateways. It's already supported by the DependencyInjectionExtension and the Omnipay Helper.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Thanks Christoph!

**Comment by CHH** [comment]
:)

Are there any plans for upgrading this bundle for Omnipay 2.0?

## 

Ing. Christoph Hochstrasser
Kapuzinergasse 6
3340 Waidhofen an der Ybbs
christoph@hochstrasser.io
+43 664 922 86 51
http://hochstrasser.io
UID: ATU68701078

Bankverbindung: Sparkasse Niederösterreich BIC: SPSPAT21XXX IBAN: AT55 2025 6000 0095 6227

Am 04.08.2014 um 13:59 schrieb Paweł Jędrzejewski notifications@github.com:

**Comment by pjedrzejewski** [comment]
We are not using it anymore in Sylius, so if there is someone interested in taking care of it and upgrading to Omnipay 2.0, I'd be more that happy. :)

Actually, we are using Omnipay, but through Payum, so this bundle is not installed.

**Comment by makasim** [comment]
just for the record. Omnipay support only pure stripe integration, where Payum provide strpipe.js and checkout support as well as pure php version.

**Pull request merged**
