### PR TITLE
add credit card interface for mapping to omnipay format

### PR DESCRIPTION
**Pull request by Eponymi**
Just a simple interface class that credit card entity's can implement so they have a method for mapping to Omnipay format before submitting to a gateway. 

I considered putting constants for all of the Omnipay properties, or writing a "mapper" class that implemented this interface and had a check for Omnipay methods named "set[whateverProperty]" but those both seemed too heavy.

This will just act as a simple reminder to implement a mapper to Omnipay format and supply the convenience method for doing that mapping.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Sounds perfect to me. I don't have idea for better name for the method, so unless @umpirsky @winzou @jjanvier have any proposition for more clear name - good to merge. :)

**Comment by stloyd** [comment]
Hmmm... what about `transformModel()` ? As `mapToOmnipay()` sounds wired for me =)

**Comment by Eponymi** [comment]
good deal, will update, method name doesn't matter to me, just having functionality in there.

**Comment by pjedrzejewski** [comment]
But `transformModel` does not really tell us what this method should do. Transform to what?

**Comment by Eponymi** [comment]
Woops, just changed it to `transformModel`. I'll wait until this gets decided on and push again.

How about `transformModelToOmnipay`? Seems to convey the meaning and gets rid of `map`.

**Comment by stloyd** [comment]
@pjedrzejewski For description you have phpdocs =)

**Comment by winzou** [comment]
`transformToOmnipay` sounds good to me (transform is better than map indeed). The method name is more explicit than phpdocs ;)

**Comment by pjedrzejewski** [comment]
@winzou @stloyd @Eponymi +1 for `transformToOmnipay`!

**Comment by pjedrzejewski** [comment]
Thank you Dylan!

**Pull request merged**
